# Continuous integration and building of the
# PDF files using the GitHub Actions
# 1) checkout
# 2) install texlive
# 3) build the PDFs
# 4) upload the PDFs as artifacts

name: CI

on:
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Builds pandoc templates 
        run: cd tests && make templates
      - name: Compile Latex Document
        uses: xu-cheng/texlive-action@v3
        with:
          run: cd tests && make all
      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: pdfs
          path: tests/*.pdf
